#%RAML 1.0 DataType
displayName: Spotify URI
type: string
pattern: ^(spotify:)(track|album|artist):[a-zA-Z0-9]+
description: |
  The resource identifier that you can enter, for example, in the Spotify
  Desktop client's search box to locate an artist, album, or track. To find
  a Spotify URI simply right-click (on Windows) or Ctrl-Click (on a Mac) on
  the artist's or album's or track's name
example: spotify:track:6rqhFgbbKwnb9MLmUQDhG6
