#%RAML 1.0 DataType
displayName: Spotify Category ID
type: string
pattern: ^[A-Za-z0-9]+
description: |
  The unique string identifying the Spotify category that you can find at the
  end of the Spotify URI for the category.
example: party
