#%RAML 1.0 DataType
type: string
displayName: Spotify User ID
pattern: ^[a-zA-Z0-9]+
description: |
  The unique string identifying the Spotify user that you can find at the
  end of the Spotify URI for the user. The ID of the current user can be
  obtained via the Web API endpoint https://api.spotify.com/v1/me.
example: wizzler
