#%RAML 1.0 DataType
displayName: Spotify ID
type: string
pattern: ^[A-Za-z0-9]+
description: |
  The base-62 identifier that you can find at the end of the Spotify URI (see
  Spotify URI) for an artist, track, album, playlist, etc. Unlike a Spotify
  URI, a Spotify ID does not clearly identify the type of resource; that
  information is provided elsewhere in the call.
example: 6rqhFgbbKwnb9MLmUQDhG6
