#%RAML 1.0 DataType
type: BasePage
displayName: Cursor Page Object
description: |
  The cursor-based paging object is a container for a set of objects. It
  contains a key called `items` (whose value is an array of the requested
  objects) along with other keys like `next` and `cursors` that can be useful
  in future calls.
properties:
  cursors:
    type: Cursor
    description: The cursors used to find the next set of items.
