#%RAML 1.0 DataType
type: object
displayName: Followers Object
description: Information about the followers of an item.
properties:
  href:
    type: string
    description: |
      A link to the Web API endpoint providing full details of the
      followers; null if not available. Please note that this will
      always be set to `null`, as the Web API does not support it
      at the moment.
  total:
    type: integer
    description: The total number of followers.
