#%RAML 1.0 DataType

displayName: Simple Playlist Object
type: object
properties:
  collaborative:
    type: boolean
    description: |
      `true` if the owner allows other users to modify the playlist.
  external_urls: ExternalUrl
  href:
    type: string
    description: |
      A link to the Web API endpoint providing full details of the playlist.
  id: SpotifyId
  images:
    type: Image[]
    description: |
      Images for the playlist. The array may be empty or contain up to three
      images. The images are returned by size in descending order. See
      [Working with Playlists](https://developer.spotify.com/web-api/working-with-playlists/).

      Note: If returned, the source URL for the image (url) is temporary and
      will expire in less than a day.
  name:
    type: string
    description: The name of the playlist.
  owner:
    type: User
    description: The user who owns the playlist.
  public:
    type: string
    enum: [ true, false, null ]
    description: |
      The playlist's public/private status: `true` the playlist is public,
      `false` the playlist is private, `null` the playlist status is not
      relevant. For more about public/private status, see [Working with
      Playlists](https://developer.spotify.com/web-api/working-with-playlists/).
  snapshot_id:
    type: string
    description: |
      The version identifier for the current playlist. Can be supplied in
      other requests to target a specific playlist version: see [Remove
      tracks from a playlist](https://developer.spotify.com/web-api/remove-tracks-playlist/).
  tracks:
    type: Page
    description: Information about the tracks of the playlist.
  type:
    type: string
    description: |
      The object type: "playlist"
  uri: SpotifyUri
