#%RAML 1.0 DataType
type: object
displayName: Saved Track Object
properties:
  added_at:
    type: string
    pattern: ^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})Z
    example: 2015-11-04T09:20:22Z
    description: |
      The date and time the track was saved.

      Timestamps are returned in [ISO 8601](http://en.wikipedia.org/wiki/ISO_8601)
      format as [Coordinated Universal Time](http://en.wikipedia.org/wiki/Offset
      _to_Coordinated_Universal_Time) (UTC) with zero offset.
      YYYY-MM-DDTHH:MM:SSZ.
  track: Track
