#%RAML 1.0 Library
types:
  Album: !include ./_album.raml
  AlbumSimple: !include ./_album_simple.raml
  Artist: !include ./_artist.raml
  ArtistSimple: !include ./_artist_simple.raml
  BasePage: !include ./_base_page.raml
  Category: !include ./_category.raml
  Copyright: !include ./_copyright.raml
  Cursor: !include ./_cursor.raml
  CursorPage: !include ./_cursor_page.raml
  Error: !include ./_error.raml
  ExternalId: !include ./_external_id.raml
  ExternalUrl: !include ./_external_url.raml
  Followers: !include ./_followers.raml
  Image: !include ./_image.raml
  Page: !include ./_page.raml
  Playlist: !include ./_playlist.raml
  PlaylistSimple: !include ./_playlist_simple.raml
  PlaylistTrack: !include ./_playlist_track.raml
  SavedTrack: !include ./_saved_track.raml
  Track: !include: ./_track.raml
  TrackLink: !include ./_track_link.raml
  TrackSimple: !include ./_track_simple.raml
  UserPrivate: !include ./_user_private.raml
  UserPublic: !include ./_user_public.raml
